### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by schoeberl** [TinyTapeout/tt04-submission-template#2]
Maybe make this a GitHuib template. See: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by urish** [comment]
Thanks for the proposal!

Unfortunately, when you generate a template, the history is not carried over, and users can't easily see if there have been any chances to the template since they created their project.

Is there a particular reason you prefer templates over forks?

**Comment by tommythorn** [comment]
Matt Vern wrote (in unlinkable Discord): "One of the annoyances of everyone forking the submission repo is that I can't open issues on people's projects. I have to open an issue on my repo and then tag them"

So that's one argument, but your point probably takes precedence

**Comment by schoeberl** [comment]
You are right.

Martin
