### ISSUE TITLE
GDS ERROR: DeprecatedConfig in `setup.cfg` (HDL project)

### ISSUE THREAD

**Issue by kosmalex** [TinyTapeout/tt04-submission-template#4]
The gds action gives me the following error while building:

× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-nu699e_u/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/runner/openlane/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()

**Comment by urish** [comment]
Tested and reproduced, thanks for reporting!

This might be related to yaml/pyyaml#601, but needs further investigation

**Comment by dlmiles** [comment]
It does seem related to this, I have an ugly workaround (that doesn't require changing the OL docker image).

Maybe you can make a tidy version :)

https://github.com/TinyTapeout/tt-gds-action/compare/main...dlmiles:tt-gds-action:tt04-dlm

**Comment by urish** [comment]
Should be fixed by TinyTapeout/tt-gds-action@038cad4121d5ee39f3323ddae153641cad107079.

Can you please try again and report?

**Comment by kosmalex** [comment]
Everything run smoothly, thanks for the quick fix! Appreciate all your help.

**Comment by kosmalex** [comment]
Since it is resolved, I'm closing it
