### ISSUE TITLE
Review config.tcl: set ::env(GRT_CELL_PADDING) "4"

### ISSUE THREAD

**Issue by dlmiles** [TinyTapeout/tt04-submission-template#6]
Please review this line:
https://github.com/TinyTapeout/tt04-submission-template/blob/main/src/config.tcl#L37

This maybe a typo of GPL_CELL_PADDING ?  Which looks used by PL_TARGET_DENSITY

Related docs: https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/openroad/gpl.tcl#L64
Related discord discussion: https://discord.com/channels/1009193568256135208/1009193884015919215/1129499909385637889

**Comment by mattvenn** [comment]
thanks, yes it's a typo. close with #d4f7630
